### ISSUE TITLE
RuntimeError: can't create new thread at interpreter shutdown

### ISSUE THREAD

**Issue by peshkoff** [mensonen/diameter#11]
After receiving new diameter request I have error. I'm using SimpleThreadingApplication with request_handler
```

2024-01-17 18:52:53,575 diameter.peer.msg DEBUG RECV dra01.s2.nw.data.pcrf.mnc999.mcc999.3gppnetwork.org
Spending-Limit <Version: 0x01, Length: 456, Flags: 0xc0 (request, proxyable), Hop-by-Hop Identifier: 0x987b8ffe, End-to-End Identifier: 0x322479>
  Session-Id <Code: 0x107, Flags: 0x40 (-M-), Length: 97, Val: pccm04.s2.nw.data.pcrf.mnc999.mcc999.3gppnetwork.org;250010000000001;Sy;63841103573572481>
  Auth-Application-Id <Code: 0x102, Flags: 0x40 (-M-), Length: 12, Val: 16777302>
  Origin-Host <Code: 0x108, Flags: 0x40 (-M-), Length: 55, Val: b'pccm.nw.data.pcrf.mnc999.mcc999.3gppnetwork.org'>
  Origin-Realm <Code: 0x128, Flags: 0x40 (-M-), Length: 50, Val: b'nw.data.pcrf.mnc999.mcc999.3gppnetwork.org'>
  Destination-Realm <Code: 0x11b, Flags: 0x40 (-M-), Length: 44, Val: b'dra.nw.mnc999.mcc999.3gppnetwork.org'>
  SL-Request-Type <Code: 0xb58, Flags: 0xc0 (VM-), Length: 16, Vnd: TGPP, Val: 0>
  Subscription-Id <Code: 0x1bb, Flags: 0x40 (-M-), Length: 44>
    Subscription-Id-Type <Code: 0x1c2, Flags: 0x40 (-M-), Length: 12, Val: 1>
    Subscription-Id-Data <Code: 0x1bc, Flags: 0x40 (-M-), Length: 23, Val: 999990000000001>
  Subscription-Id <Code: 0x1bb, Flags: 0x40 (-M-), Length: 40>
    Subscription-Id-Type <Code: 0x1c2, Flags: 0x40 (-M-), Length: 12, Val: 0>
    Subscription-Id-Data <Code: 0x1bc, Flags: 0x40 (-M-), Length: 19, Val: 99999000001>
  Route-Record <Code: 0x11a, Flags: 0x40 (-M-), Length: 60, Val: b'pccm04.s2.nw.data.pcrf.mnc999.mcc999.3gppnetwork.org'>
  Framed-IP-Address <Code: 0x08, Flags: 0x40 (-M-), Length: 12, Val: b'\xa4kq\x12'>

===================== start thr
Exception in thread Thread-5 (_wait_for_recv_msg):
Traceback (most recent call last):
  File "/opt/python/3.12.1/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/opt/python/3.12.1/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/python/3.12.1/lib/python3.12/site-packages/diameter/node/application.py", line 324, in _wait_for_recv_msg
    process_message.start()
  File "/opt/python/3.12.1/lib/python3.12/threading.py", line 992, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't create new thread at interpreter shutdown

```

**Comment by mensonen** [comment]
This is essentially a race condition that happens if the application receives a message at exactly the same time as the python interpreter shuts down. This error is new to Python 3.12, as an explicit check for this scenario was added: https://github.com/python/cpython/commit/ce558e69d4087dd3653207de78345fbb8a2c7835. Python 3.11 does not produce this error.

There's not much to do here, the application obviously cannot process the received message as the interpreter is already shutting down. I can (and will) add checks to the few places where a thread is being spawned, in order to silence this.

Could you let me know *how* you stopped the node? Normally, if you just call `Node.stop()`, there should be a sufficient grace period to let all applications and peers to wind down and this race condition should already be avoided. Did you perhaps just kill the entire interpreter, e.g. with a SIGTERM or SIGKILL?

**Comment by peshkoff** [comment]
No. It's crashing when receiving SLR init. And only the  thread instance crashing. The main script continues to run. Second message (retransmited) is not processed 

```
2024-01-18 11:45:52,376 diameter.peer.msg DEBUG RECV dra01.s2.nw.data.pcrf.mnc999.mcc999.3gppnetwork.org
Spending-Limit <Version: 0x01, Length: 456, Flags: 0xc0 (request, proxyable), Hop-by-Hop Identifier: 0x21ec927b, End-to-End Identifier: 0x35b7b3>
  Session-Id <Code: 0x107, Flags: 0x40 (-M-), Length: 97, Val: pccm04.s2.nw.data.pcrf.mnc999.mcc999.3gppnetwork.org;250010000000001;Sy;63841164352374102>
  Auth-Application-Id <Code: 0x102, Flags: 0x40 (-M-), Length: 12, Val: 16777302>
  Origin-Host <Code: 0x108, Flags: 0x40 (-M-), Length: 55, Val: b'pccm.nw.data.pcrf.mnc999.mcc999.3gppnetwork.org'>
  Origin-Realm <Code: 0x128, Flags: 0x40 (-M-), Length: 50, Val: b'nw.data.pcrf.mnc999.mcc999.3gppnetwork.org'>
  Destination-Realm <Code: 0x11b, Flags: 0x40 (-M-), Length: 44, Val: b'dra.nw.mnc999.mcc999.3gppnetwork.org'>
  SL-Request-Type <Code: 0xb58, Flags: 0xc0 (VM-), Length: 16, Vnd: TGPP, Val: 0>
  Subscription-Id <Code: 0x1bb, Flags: 0x40 (-M-), Length: 44>
    Subscription-Id-Type <Code: 0x1c2, Flags: 0x40 (-M-), Length: 12, Val: 1>
    Subscription-Id-Data <Code: 0x1bc, Flags: 0x40 (-M-), Length: 23, Val: 999990000000001>
  Subscription-Id <Code: 0x1bb, Flags: 0x40 (-M-), Length: 40>
    Subscription-Id-Type <Code: 0x1c2, Flags: 0x40 (-M-), Length: 12, Val: 0>
    Subscription-Id-Data <Code: 0x1bc, Flags: 0x40 (-M-), Length: 19, Val: 99999000001>
  Route-Record <Code: 0x11a, Flags: 0x40 (-M-), Length: 60, Val: b'pccm04.s2.nw.data.pcrf.mnc999.mcc999.3gppnetwork.org'>
  Framed-IP-Address <Code: 0x08, Flags: 0x40 (-M-), Length: 12, Val: b'\xa4kq\x12'>

===================== start thr
Exception in thread Thread-5 (_wait_for_recv_msg):
Traceback (most recent call last):
  File "/opt/python/3.12.1/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/opt/python/3.12.1/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/python/3.12.1/lib/python3.12/site-packages/diameter/node/application.py", line 324, in _wait_for_recv_msg
    process_message.start()
  File "/opt/python/3.12.1/lib/python3.12/threading.py", line 992, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't create new thread at interpreter shutdown
2024-01-18 11:45:56,157 diameter.peer.msg DEBUG RECV dra01.s2.nw.data.pcrf.mnc999.mcc999.3gppnetwork.org
Device-Watchdog <Version: 0x01, Length: 136, Flags: 0x80 (request), Hop-by-Hop Identifier: 0x21ec927c, End-to-End Identifier: 0x847fa>
  Origin-Host <Code: 0x108, Flags: 0x40 (-M-), Length: 59, Val: b'dra01.s2.nw.data.pcrf.mnc999.mcc999.3gppnetwork.org'>
  Origin-Realm <Code: 0x128, Flags: 0x40 (-M-), Length: 44, Val: b'dra.nw.mnc999.mcc999.3gppnetwork.org'>
  Origin-State-Id <Code: 0x116, Flags: 0x40 (-M-), Length: 12, Val: 1705562816>

2024-01-18 11:45:56,159 diameter.peer.msg DEBUG SENT dra01.s2.nw.data.pcrf.mnc999.mcc999.3gppnetwork.org
Device-Watchdog <Version: 0x01, Length: 148, Flags: 0x00 (), Hop-by-Hop Identifier: 0x21ec927c, End-to-End Identifier: 0x847fa>
  Result-Code <Code: 0x10c, Flags: 0x40 (-M-), Length: 12, Val: 2001>
  Origin-Host <Code: 0x108, Flags: 0x40 (-M-), Length: 57, Val: b'test_dsr_sy.dra.nw.mnc999.mcc999.3gppnetwork.org'>
  Origin-Realm <Code: 0x128, Flags: 0x40 (-M-), Length: 44, Val: b'dra.nw.mnc999.mcc999.3gppnetwork.org'>
  Origin-State-Id <Code: 0x116, Flags: 0x40 (-M-), Length: 12, Val: 1705567545>

**retranmitted message**
2024-01-18 11:45:58,577 diameter.peer.msg DEBUG RECV dra01.s2.nw.data.pcrf.mnc999.mcc999.3gppnetwork.org
Spending-Limit <Version: 0x01, Length: 456, Flags: 0xc0 (request, proxyable), Hop-by-Hop Identifier: 0x21ec927d, End-to-End Identifier: 0x35b7c5>
  Session-Id <Code: 0x107, Flags: 0x40 (-M-), Length: 97, Val: pccm04.s2.nw.data.pcrf.mnc999.mcc999.3gppnetwork.org;250010000000001;Sy;63841164358575041>
  Auth-Application-Id <Code: 0x102, Flags: 0x40 (-M-), Length: 12, Val: 16777302>
  Origin-Host <Code: 0x108, Flags: 0x40 (-M-), Length: 55, Val: b'pccm.nw.data.pcrf.mnc999.mcc999.3gppnetwork.org'>
  Origin-Realm <Code: 0x128, Flags: 0x40 (-M-), Length: 50, Val: b'nw.data.pcrf.mnc999.mcc999.3gppnetwork.org'>
  Destination-Realm <Code: 0x11b, Flags: 0x40 (-M-), Length: 44, Val: b'dra.nw.mnc999.mcc999.3gppnetwork.org'>
  SL-Request-Type <Code: 0xb58, Flags: 0xc0 (VM-), Length: 16, Vnd: TGPP, Val: 0>
  Subscription-Id <Code: 0x1bb, Flags: 0x40 (-M-), Length: 44>
    Subscription-Id-Type <Code: 0x1c2, Flags: 0x40 (-M-), Length: 12, Val: 1>
    Subscription-Id-Data <Code: 0x1bc, Flags: 0x40 (-M-), Length: 23, Val: 999990000000001>
  Subscription-Id <Code: 0x1bb, Flags: 0x40 (-M-), Length: 40>
    Subscription-Id-Type <Code: 0x1c2, Flags: 0x40 (-M-), Length: 12, Val: 0>
    Subscription-Id-Data <Code: 0x1bc, Flags: 0x40 (-M-), Length: 19, Val: 99999000001>
  Route-Record <Code: 0x11a, Flags: 0x40 (-M-), Length: 60, Val: b'pccm04.s2.nw.data.pcrf.mnc999.mcc999.3gppnetwork.org'>
  Framed-IP-Address <Code: 0x08, Flags: 0x40 (-M-), Length: 12, Val: b'\xa4kq\x12'>

2024-01-18 11:46:06,168 diameter.peer.msg DEBUG RECV dra01.s2.nw.data.pcrf.mnc999.mcc999.3gppnetwork.org
Device-Watchdog <Version: 0x01, Length: 136, Flags: 0x80 (request), Hop-by-Hop Identifier: 0x21ec927e, End-to-End Identifier: 0x847fc>
  Origin-Host <Code: 0x108, Flags: 0x40 (-M-), Length: 59, Val: b'dra01.s2.nw.data.pcrf.mnc999.mcc999.3gppnetwork.org'>
  Origin-Realm <Code: 0x128, Flags: 0x40 (-M-), Length: 44, Val: b'dra.nw.mnc999.mcc999.3gppnetwork.org'>
  Origin-State-Id <Code: 0x116, Flags: 0x40 (-M-), Length: 12, Val: 1705562816>

2024-01-18 11:46:06,169 diameter.peer.msg DEBUG SENT dra01.s2.nw.data.pcrf.mnc999.mcc999.3gppnetwork.org
Device-Watchdog <Version: 0x01, Length: 148, Flags: 0x00 (), Hop-by-Hop Identifier: 0x21ec927e, End-to-End Identifier: 0x847fc>
  Result-Code <Code: 0x10c, Flags: 0x40 (-M-), Length: 12, Val: 2001>
  Origin-Host <Code: 0x108, Flags: 0x40 (-M-), Length: 57, Val: b'test_dsr_sy.dra.nw.mnc999.mcc999.3gppnetwork.org'>
  Origin-Realm <Code: 0x128, Flags: 0x40 (-M-), Length: 44, Val: b'dra.nw.mnc999.mcc999.3gppnetwork.org'>
  Origin-State-Id <Code: 0x116, Flags: 0x40 (-M-), Length: 12, Val: 1705567545>

```

**Comment by mensonen** [comment]
The crash in the application thread does happen because the main python interpreter is shutting down; the RuntimeError comes from python itself, not from the diameter stack. I'm guessing something is already happening before the SLR arrives, causing the interpreter to shut down. After that point it's impossible to spawn new threads, but the already existing ones seem to continue running uninterrupted.

Can you provide a .pcap of the message that causes the crash? I'll try to reproduce it. Also share the entire log file if possible, or at least a snippet with several lines before the received message dump.

**Comment by peshkoff** [comment]
Yes. It's crashing when SLR is come for the first time. Message is from previously provided pcap, attached again 
[app.log](https://github.com/mensonen/diameter/files/13974615/app.log)
[slr.zip](https://github.com/mensonen/diameter/files/13974616/slr.zip)

**Comment by peshkoff** [comment]
May be I should try python 3.11?

**Comment by mensonen** [comment]
Does your `sy_emulator.py` have a busy loop after calling `Node.start()`? I.e should look something like this:

```python
node.start()

server = Server(application_id=APP_3GPP_SY, is_auth_application=True)
node.add_application(server, [])

try:
    while True:
        time.sleep(1)

except (KeyboardInterrupt, SystemExit) as e:
    node.stop()
```

From your logfile I can see that the Node instance is at least not trying to stop on its own, so I'm guessing something in your python script causes it to exit without calling `Node.stop()` first.

**Comment by peshkoff** [comment]
> Does your `sy_emulator.py` have a busy loop after calling `Node.start()`? I.e should look something like this:
> 
> ```python
> node.start()
> 
> server = Server(application_id=APP_3GPP_SY, is_auth_application=True)
> node.add_application(server, [])
> 
> try:
>     while True:
>         time.sleep(1)
> 
> except (KeyboardInterrupt, SystemExit) as e:
>     node.stop()
> ```
> 
> From your logfile I can see that the Node instance is at least not trying to stop on its own, so I'm guessing something in your python script causes it to exit without calling `Node.stop()` first.

That's was the fix! Thank You very much! My mistake

**Comment by mensonen** [comment]
Great. I will still add a fix for the RuntimeError being raised. In your case it was just a programmer error, but there are edge cases where the error might arise under normal operations.
